model: yolov5n-cls.pt
data: C:\tea_yolov5_training\data
epochs: 50
batch_size: 32
imgsz: 224
nosave: false
cache: null
device: cpu
workers: 4
project: C:\tea_yolov5_training\runs\classify
name: tea_pests_cls_yolov5
exist_ok: true
pretrained: true
optimizer: Adam
lr0: 0.001
decay: 5.0e-05
label_smoothing: 0.1
cutoff: null
dropout: null
verbose: false
seed: 42
local_rank: -1
roboflow_token: null
save_dir: C:\tea_yolov5_training\runs\classify\tea_pests_cls_yolov5
